version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  app:
    image: node:alpine
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5000:5000"
    command: >
      sh -c "chmod +x ./node_modules/.bin/* && npm run build && npm start"
    depends_on:
      - postgres
